export const menuMockData = [
    {
        id: "1003414",
        name: "Pizza Hut",
        cuisines: ["Pizzas"],
        menu: ["Margherita Pizza", "Pepperoni Pizza", "BBQ Chicken Pizza", "Farm House Pizza", "Garlic Bread", "Choco Lava Cake"],
    },
    {
        id: "150602",
        name: "Raimens Cafe 79",
        cuisines: ["Bakery", "Pizzas", "Snacks", "Beverages"],
        menu: ["Chocolate Cake", "Veg Pizza", "French Fries", "Cold Coffee", "Sandwich"],
    },
    {
        id: "151656",
        name: "Dev International",
        cuisines: ["Chinese", "Fast Food", "Beverages"],
        menu: ["Veg Fried Rice", "Chowmein", "Manchurian", "Spring Rolls", "Lemon Soda"],
    },
    {
        id: "234875",
        name: "Adil Hotel",
        cuisines: ["Biryani", "Tandoor"],
        menu: ["Chicken Biryani", "Veg Biryani", "Tandoori Roti", "Dal Makhani", "Paneer Tikka"],
    },
    {
        id: "1316369",
        name: "Epic Bite",
        cuisines: ["Biryani", "North Indian", "Mughlai"],
        menu: ["Mutton Biryani", "Butter Chicken", "Naan", "Seekh Kebab", "Raita"],
    },
    {
        id: "618037",
        name: "Jai Ganesh Bhojnalaya",
        cuisines: ["South Indian", "Indian", "Chinese"],
        menu: ["Masala Dosa", "Idli Sambar", "Thali", "Hakka Noodles", "Lassi"],
    },
    {
        id: "151518",
        name: "Bakery World",
        cuisines: ["Bakery", "Ice Cream", "Snacks", "Beverages"],
        menu: ["Puff Pastry", "Vanilla Ice Cream", "Brownie", "Croissant", "Milkshake"],
    },
    {
        id: "1271089",
        name: "City Restaurant",
        cuisines: ["North Indian"],
        menu: ["Dal Tadka", "Jeera Rice", "Roti", "Paneer Butter Masala", "Kheer"],
    },
    {
        id: "1098358",
        name: "Top N Town Ice Cream",
        cuisines: ["Desserts", "Ice Cream"],
        menu: ["Mango Ice Cream", "Butterscotch Cone", "Chocolate Sundae", "Fruit Salad", "Kulfi"],
    },
    {
        id: "1211364",
        name: "Pizza Wala",
        cuisines: ["Italian", "Pizzas", "Fast Food", "Burgers"],
        menu: ["Classic Pizza", "Veggie Burger", "Pasta Arrabiata", "Garlic Bread", "Soft Drink"],
    },
    {
        id: "151649",
        name: "Hotel Sai Nath & Sai Restaurant",
        cuisines: ["North Indian", "South Indian", "Chinese"],
        menu: ["Masala Chai", "Veg Thali", "Fried Rice", "Samosa", "Gulab Jamun"],
    },
    {
        id: "151648",
        name: "Mr. Gurung Momo & Chinese Corner",
        cuisines: ["Momos", "Chinese", "Fast Food"],
        menu: ["Steamed Momos", "Fried Momos", "Wonton Soup", "Chilli Chicken", "Thukpa"],
    },
    {
        id: "912754",
        name: "Urban Cafe",
        cuisines: ["Snacks", "Pizzas", "Burgers", "Cafe"],
        menu: ["Cappuccino", "Veg Burger", "Loaded Fries", "Mini Pizza", "Chocolate Waffle"],
    },
    {
        id: "256341",
        name: "Burger King",
        cuisines: ["Burgers", "American", "Fast Food"],
        menu: ["Whopper", "Crispy Chicken Burger", "Onion Rings", "Veggie Burger", "Milkshake"],
    },
    {
        id: "956234",
        name: "Subway",
        cuisines: ["Healthy Food", "Salads", "Snacks"],
        menu: ["Veggie Delight Sub", "Chicken Teriyaki Sub", "Caesar Salad", "Cookies", "Lemonade"],
    },
    {
        id: "478923",
        name: "Domino's Pizza",
        cuisines: ["Pizzas", "Italian", "Fast Food"],
        menu: ["Cheese Burst Pizza", "Veg Extravaganza", "Pasta Italiano", "Choco Lava Cake", "Garlic Bread Sticks"],
    },
    {
        id: "512789",
        name: "Cafe Coffee Day",
        cuisines: ["Cafe", "Beverages", "Desserts", "Snacks"],
        menu: ["Cold Coffee", "Espresso", "Chocolate Muffin", "Veg Sandwich", "Pastry"],
    },
    {
        id: "1209158",
        name: "Trio Cafe",
        cuisines: ["Cafe"],
        menu: ["Latte", "Cappuccino", "Banana Bread", "Club Sandwich", "Brownie"],
    },
    {
        id: "734512",
        name: "Chinese Wok",
        cuisines: ["Chinese", "Asian", "Tibetan"],
        menu: ["Dragon Chicken", "Veg Fried Rice", "Dim Sum", "Szechuan Noodles", "Hot & Sour Soup"],
    },
    {
        id: "845623",
        name: "KFC",
        cuisines: ["Burgers", "Biryani", "Fast Food"],
        menu: ["Zinger Burger", "Popcorn Chicken", "Hot Wings", "Rice Bowl", "Coleslaw"],
    },
];
